<a href="https://colab.research.google.com/github/VikasBadal08/student_data_analysis/blob/main/miniprj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  pandas as pd

In [ ]:
df=pd.read_csv("/content/student_dataset.csv")
df

   Student_ID    Name  Gender  Maths  Science  English  Attendance
0         101    Amit    Male     78       85       80          90
1         102   Priya  Female     92       88       95          96
2         103   Rahul    Male     65       70       60          75
3         104   Sneha  Female     88       91       84          93
4         105   Karan    Male     55       60       58          68
5         106    Neha  Female     95       98       97          99
6         107   Arjun    Male     72       75       70          82
7         108   Pooja  Female     81       79       85          89
8         109   Vikas    Male     60       64       62          71
9         110  Anjali  Female     90       92       94          97

In [ ]:
# • Display first few rows
df.head()

   Student_ID   Name  Gender  Maths  Science  English  Attendance
0         101   Amit    Male     78       85       80          90
1         102  Priya  Female     92       88       95          96
2         103  Rahul    Male     65       70       60          75
3         104  Sneha  Female     88       91       84          93
4         105  Karan    Male     55       60       58          68

In [ ]:
# • Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Gender      10 non-null     object
 3   Maths       10 non-null     int64
 4   Science     10 non-null     int64
 5   English     10 non-null     int64
 6   Attendance  10 non-null     int64
dtypes: int64(5), object(2)
memory usage: 692.0+ bytes

In [ ]:
#  Check number of rows and columns

df.shape
print(f"no of raw is :{df.shape[0]}")
print(f"no of column is :{df.shape[1]}")

no of raw is :10
no of column is :7

In [ ]:
# • Check null values
df.isnull().sum()

Student_ID    0
Name          0
Gender        0
Maths         0
Science       0
English       0
Attendance    0
dtype: int64

In [ ]:
# • Remove duplicate records
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
duplicates = df[df.duplicated()]

In [ ]:
#  Verify data types
df.dtypes

Student_ID     int64
Name          object
Gender        object
Maths          int64
Science        int64
English        int64
Attendance     int64
dtype: object

In [ ]:
#  Handle missing values if present
print("no null value is pressent")

no null value is pressent

In [ ]:
# • Calculate total marks
df["Total"]=df['English']+df['Maths']+df['Science']
print(df)

   Student_ID    Name  Gender  Maths  Science  English  Attendance  Total
0         101    Amit    Male     78       85       80          90    243
1         102   Priya  Female     92       88       95          96    275
2         103   Rahul    Male     65       70       60          75    195
3         104   Sneha  Female     88       91       84          93    263
4         105   Karan    Male     55       60       58          68    173
5         106    Neha  Female     95       98       97          99    290
6         107   Arjun    Male     72       75       70          82    217
7         108   Pooja  Female     81       79       85          89    245
8         109   Vikas    Male     60       64       62          71    186
9         110  Anjali  Female     90       92       94          97    276

In [ ]:
# Calculate percentage
total_marks=300 # 3*100
df['Percentage']=(df["Total"]/total_marks)*100
print(df)

   Student_ID    Name  Gender  Maths  Science  English  Attendance  Total  \
0         101    Amit    Male     78       85       80          90    243
1         102   Priya  Female     92       88       95          96    275
2         103   Rahul    Male     65       70       60          75    195
3         104   Sneha  Female     88       91       84          93    263
4         105   Karan    Male     55       60       58          68    173
5         106    Neha  Female     95       98       97          99    290
6         107   Arjun    Male     72       75       70          82    217
7         108   Pooja  Female     81       79       85          89    245
8         109   Vikas    Male     60       64       62          71    186
9         110  Anjali  Female     90       92       94          97    276

   Percentage
0   81.000000
1   91.666667
2   65.000000
3   87.666667
4   57.666667
5   96.666667
6   72.333333
7   81.666667
8   62.000000
9   92.000000

In [ ]:
# Assign grades based on percentage
def grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F"

df["Grade"] = df["Percentage"].apply(grade)
df

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Total,Percentage,Grade
0,101,Amit,Male,78,85,80,90,243,81.000000,A
1,102,Priya,Female,92,88,95,96,275,91.666667,A+
2,103,Rahul,Male,65,70,60,75,195,65.000000,C
3,104,Sneha,Female,88,91,84,93,263,87.666667,A
4,105,Karan,Male,55,60,58,68,173,57.666667,D
5,106,Neha,Female,95,98,97,99,290,96.666667,A+
6,107,Arjun,Male,72,75,70,82,217,72.333333,B
7,108,Pooja,Female,81,79,85,89,245,81.666667,A
8,109,Vikas,Male,60,64,62,71,186,62.000000,C
9,110,Anjali,Female,90,92,94,97,276,92.000000,A+

In [ ]:
# • Top performing student

top_std=df.loc[df['Total'].idxmax()]
top_std

Student_ID          106
Name               Neha
Gender           Female
Maths                95
Science              98
English              97
Attendance           99
Total               290
Percentage    96.666667
Grade                A+
Name: 5, dtype: object

In [ ]:
# • Lowest performing student
lowest_std=df.loc[df['Total'].idxmin()]
lowest_std

Student_ID          105
Name              Karan
Gender             Male
Maths                55
Science              60
English              58
Attendance           68
Total               173
Percentage    57.666667
Grade                 D
Name: 4, dtype: object

In [ ]:
# • Average marks in each subject
sub=['English','Maths','Science']
av=df[sub].mean()
print(av)

English    78.5
Maths      77.6
Science    80.2
dtype: float64

In [ ]:
# • Highest attendance
high_att=df.loc[df['Attendance'].idxmax()]
high_att

Student_ID          106
Name               Neha
Gender           Female
Maths                95
Science              98
English              97
Attendance           99
Total               290
Percentage    96.666667
Grade                A+
Name: 5, dtype: object

In [ ]:
#  Students scoring below average
average=df['Total'].mean()
below_avg=df[df["Total"]<average]
below_avg

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Total,Percentage,Grade
2,103,Rahul,Male,65,70,60,75,195,65.000000,C
4,105,Karan,Male,55,60,58,68,173,57.666667,D
6,107,Arjun,Male,72,75,70,82,217,72.333333,B
8,109,Vikas,Male,60,64,62,71,186,62.000000,C

In [ ]:
# • Gender-wise average performance
avg_per=df.groupby('Gender')['Total'].mean()
avg_per

Gender
Female    269.8
Male      202.8
Name: Total, dtype: float64

In [ ]:
df.to_csv("output.csv")